"""empty message

Revision ID: 544a506c4938
Revises: cdf45a848eca
Create Date: 2026-05-23 00:21:30.814300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544a506c4938'
down_revision = 'cdf45a848eca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=200), nullable=True))
        batch_op.drop_column('urls')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('contents_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urls', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('url')

    # ### end Alembic commands ###
