"""columna perdida bug

Revision ID: 674000583b9f
Revises: fab75be644d3
Create Date: 2026-05-28 22:01:24.577221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '674000583b9f'
down_revision = 'fab75be644d3'
branch_labels = None
depends_on = None


def upgrade():
    enum_genre_post = sa.Enum('ACCION', 'ROMANCE', 'TERROR', 'FANTASIA', 'SCIFI', name='enum_genre_post')
    enum_genre_post.create(op.get_bind())
    # el resto del código que ya está ahí...
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents_posts', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('type')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('principal_genre', sa.Enum('ACCION', 'ROMANCE', 'TERROR', 'FANTASIA', 'SCIFI', name='enum_genre_post'), nullable=False))
        batch_op.add_column(sa.Column('secondary_genre', sa.Enum('ACCION', 'ROMANCE', 'TERROR', 'FANTASIA', 'SCIFI', name='enum_genre_post'), nullable=True))
        batch_op.add_column(sa.Column('cover', sa.String(length=200), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    sa.Enum(name='enum_genre_post').drop(op.get_bind())
    sa.Enum(name='enum_category_post').drop(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('cover')
        batch_op.drop_column('secondary_genre')
        batch_op.drop_column('principal_genre')

    with op.batch_alter_table('contents_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', postgresql.ENUM('GIF', 'IMAGE', 'VIDEO', 'TEXT', name='enum_type_media'), autoincrement=False, nullable=True))
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
