"""empty message

Revision ID: a3b30ad4b8a9
Revises: 
Create Date: 2026-06-01 23:56:56.158910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b30ad4b8a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password', sa.String(length=180), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('followers',
    sa.Column('users_followed', sa.Integer(), nullable=False),
    sa.Column('users_follower', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['users_followed'], ['users.id'], ),
    sa.ForeignKeyConstraint(['users_follower'], ['users.id'], ),
    sa.PrimaryKeyConstraint('users_followed', 'users_follower')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('ONLY_TEXT', 'COMIC', name='enum_category_post'), nullable=False),
    sa.Column('principal_genre', sa.Enum('ACCION', 'ROMANCE', 'TERROR', 'FANTASIA', 'SCIFI', name='enum_genre_post'), nullable=False),
    sa.Column('secondary_genre', sa.Enum('ACCION', 'ROMANCE', 'TERROR', 'FANTASIA', 'SCIFI', name='enum_genre_post'), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('cover', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_picture', sa.String(length=250), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('artist_type', sa.Enum('COMIC_ARTIST', 'WRITER', 'HYBRID', 'READER', name='enum_artist'), nullable=True),
    sa.Column('instagram', sa.String(length=180), nullable=True),
    sa.Column('twitter', sa.String(length=180), nullable=True),
    sa.Column('facebook', sa.String(length=180), nullable=True),
    sa.Column('otros', sa.String(length=180), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('liked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contents_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_user_post_saved')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved')
    op.drop_table('contents_posts')
    op.drop_table('comments')
    op.drop_table('Likes')
    op.drop_table('profiles')
    op.drop_table('posts')
    op.drop_table('followers')
    op.drop_table('users')
    # ### end Alembic commands ###
