"""empty message

Revision ID: cdf45a848eca
Revises: 53b5571eff6a
Create Date: 2026-05-21 01:12:52.328048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cdf45a848eca'
down_revision = '53b5571eff6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urls', sa.String(length=200), nullable=True))
        batch_op.drop_column('url')
        batch_op.drop_column('type')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secondary_genre', sa.Enum('ACCION', 'ROMANCE', 'TERROR', 'FANTASIA', 'SCIFI', name='enum_genre_post'), nullable=True))
        batch_op.add_column(sa.Column('cover', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('cover')
        batch_op.drop_column('secondary_genre')

    with op.batch_alter_table('contents_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', postgresql.ENUM('GIF', 'IMAGE', 'TEXT', name='enum_type_media'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('urls')

    # ### end Alembic commands ###
